name: olamall_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+37

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_swiper: ^1.1.6            #banner插件
  flutter_screenutil: ^0.5.3        #屏幕适配插件
  dio: ^2.1.7                       #网络请求插件
  shared_preferences: ^0.5.5      #sp操作插件
  flutter_easyrefresh: ^2.0.9       #刷新加载操作
  fluttertoast: ^3.1.3              #Toast工具类
#  flutter_inappbrowser: ^1.2.1
  flutter_html: ^0.11.1
  woo_commerce_api_dart: ^0.0.3
  event_bus: ^1.1.0
  qr_flutter: ^3.2.0
  flutter_bugly: ^0.1.1
  sharesdk_plugin:
#  webview_flutter: ^0.3.18+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/
    - images/icon_commodity_back.png
    - images/2.0x/icon_commodity_back.png
    - images/3.0x/icon_commodity_back.png
    - images/icon_commodity_shop_car.png
    - images/2.0x/icon_commodity_shop_car.png
    - images/3.0x/icon_commodity_shop_car.png
    - images/icon_commodity_share.png
    - images/2.0x/icon_commodity_share.png
    - images/3.0x/icon_commodity_share.png
    - images/ic_car_wraning.png
    - images/2.0x/ic_car_wraning.png
    - images/3.0x/ic_car_wraning.png
    - images/ic_product_car.png
    - images/2.0x/ic_product_car.png
    - images/3.0x/ic_product_car.png
    - images/ic_product_sort.png
    - images/2.0x/ic_product_sort.png
    - images/3.0x/ic_product_sort.png
    - images/ic_product_screen.png
    - images/2.0x/ic_product_screen.png
    - images/3.0x/ic_product_screen.png
    - images/2.0x/ic_retrieve_password.png
    - images/3.0x/ic_retrieve_password.png
    - images/ic_retrieve_password.png
    - images/ic_mine_bg.png
    - images/2.0x/ic_mine_bg.png
    - images/3.0x/ic_mine_bg.png
    - images/ic_mine_star.png
    - images/2.0x/ic_mine_star.png
    - images/3.0x/ic_mine_star.png
    - images/ic_card_question.png
    - images/2.0x/ic_card_question.png
    - images/3.0x/ic_card_question.png
    - images/ic_master_card.png
    - images/2.0x/ic_master_card.png
    - images/3.0x/ic_master_card.png
    - images/ic_visa_card.png
    - images/2.0x/ic_visa_card.png
    - images/3.0x/ic_visa_card.png
    - images/ic_credit_card.png
    - images/2.0x/ic_credit_card.png
    - images/3.0x/ic_credit_card.png
    - images/ic_card_b.png
    - images/ic_imaginary_line.png
    - images/2.0x/ic_imaginary_line.png
    - images/3.0x/ic_imaginary_line.png
    - images/ic_right_arrows.png
    - images/2.0x/ic_right_arrows.png
    - images/3.0x/ic_right_arrows.png
    - images/ic_address_edit.png
    - images/2.0x/ic_address_edit.png
    - images/3.0x/ic_address_edit.png
    - images/ic_order_tips.png
    - images/2.0x/ic_order_tips.png
    - images/3.0x/ic_order_tips.png
    - images/ic_pay_success.png
    - images/2.0x/ic_pay_success.png
    - images/3.0x/ic_pay_success.png
    - images/ic_cd_dvd.png
    - images/2.0x/ic_cd_dvd.png
    - images/3.0x/ic_cd_dvd.png
    - images/ic_heath.png
    - images/2.0x/ic_heath.png
    - images/3.0x/ic_heath.png
    - images/ic_home_bg1.png
    - images/2.0x/ic_home_bg1.png
    - images/3.0x/ic_home_bg1.png
    - images/ic_home_bg2.png
    - images/2.0x/ic_home_bg2.png
    - images/3.0x/ic_home_bg2.png
    - images/ic_home_living.png
    - images/2.0x/ic_home_living.png
    - images/3.0x/ic_home_living.png
    - images/ic_kids_fashion.png
    - images/2.0x/ic_kids_fashion.png
    - images/3.0x/ic_kids_fashion.png
    - images/ic_search.png
    - images/2.0x/ic_search.png
    - images/3.0x/ic_search.png
    - images/ic_shoes.png
    - images/2.0x/ic_shoes.png
    - images/3.0x/ic_shoes.png
    - images/ic_go_back.png
    - images/ic_qr_code.png
    - images/2.0x/ic_qr_code.png
    - images/3.0x/ic_qr_code.png
    - images/ic_downline.png
    - images/2.0x/ic_downline.png
    - images/3.0x/ic_downline.png
    - images/ic_commission.png
    - images/2.0x/ic_commission.png
    - images/3.0x/ic_commission.png
    - images/ic_distribution_squre.png
    - images/2.0x/ic_distribution_squre.png
    - images/3.0x/ic_distribution_squre.png
    - images/ic_bank_card.png
    - images/2.0x/ic_bank_card.png
    - images/3.0x/ic_bank_card.png
    - images/ic_distribution_bg.png
    - images/2.0x/ic_distribution_bg.png
    - images/3.0x/ic_distribution_bg.png
    - images/ic_wallet_bank_card.png
    - images/2.0x/ic_wallet_bank_card.png
    - images/3.0x/ic_wallet_bank_card.png
    - images/ic_wallet_details.png
    - images/2.0x/ic_wallet_details.png
    - images/3.0x/ic_wallet_details.png
    - images/bg_rules.png
    - images/2.0x/bg_rules.png
    - images/3.0x/bg_rules.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
